"""change location

Revision ID: 1d5f31db09e1
Revises: 94b3f04b81f8
Create Date: 2023-11-11 03:11:08.875763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5f31db09e1'
down_revision: Union[str, None] = '94b3f04b81f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
